version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gambling
      MYSQL_DATABASE: model1
    volumes:
      - ./BDD:/docker-entrypoint-initdb.d/:ro


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
